version: "3.8"

volumes:
  uploads:
    driver: local
  logs:
    driver: local
  mysql:
    driver: local

services:
  mysql:
    image: mariadb:10.5
    container_name: mysql_ospos
    restart: always
    volumes:
      - mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=pointofsale
      - MYSQL_DATABASE=ospos
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pointofsale

  ospos:
    image: jekkos/opensourcepos:latest
    container_name: ospos
    restart: always
    depends_on:
      - mysql
    expose:
      - "80"
    volumes:
      - uploads:/app/public/uploads
      - logs:/app/app/logs
    environment:
      - CI_ENVIRONMENT=production
      - ALLOWED_HOSTNAMES=localhost
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=pointofsale
      - MYSQL_DB_NAME=ospos
      - MYSQL_HOST_NAME=mysql
      - PHP_TIMEZONE=UTC